nome = input("Insira o seu nome: ")
valor1 = float(input("Insira o primeiro valor: "))
valor2 = float(input("Insira o segundo valor: "))
print("Ola, meu nome é", nome ,"tenho o valor de", valor1+valor2 , " a receber")
print(f"Ola, meu nome é" {nome} "tenho o valor de" {valor1+valor2} " a receber")